name: Build release artifact.
on:
  release:
    types: [ published ]
jobs:
  tag:
    name: Build release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Create release artifact.
        run: zip -r btcpay.ocmod.zip upload -x '*/.git*'
      - name: Upload artifact to release page.
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "$GITHUB_REF_NAME" btcpay.ocmod.zip --clobber
